In [1]:
import numpy as np

In [4]:
dim = 50

In [5]:
np.sin(1/10000**(1/dim))

0.7391205490454961

- transformer는 recurrence도 아니고 convolution도 아니기 때문에, 단어의 sequence를 이용하기 위해서는 단어의 position에 대한 정보를 추가할 필요가 있음. 그래서 endcoder와 decoder의 input embedding에 positionla encoding을 더해줌. 


- positional encoding은 <em><string>d</string></em><sub>model</sub>(embedding의 차원)과 같은 차원을 갖기 때문에 positional encoding vector와 embedding vector는 더해질 수 있음


- 논문에서는 다른 frequency(주어진 구간 내에서 완료되는 cycle 횟수)를 가지고 sin과 cos 함수를 이용함 

- pos는 position, i 는 dimention이고 주기가 10000<sup>2i/dmodel</sup> * 2π인 삼각함수임.
- 즉 pos는 sequence에서 단어의 위치이고, 해당 단어는 i에 0부터 d<sup>model</sup> / 2까지를 대입해 d<sup>model</sup> 차원의 positional encoding vector를 얻게 됨.

In [6]:
def positional_encoding1(sentence_length, dim):
    encoded_vec = []
    for pos in range(sentence_length):
        for i in range(dim):
            vec = pos/10000**(2*i/dim)
            
            if i%2 == 0:
                vec = np.sin(vec)
            else:
                vec = np.cos(vec)
            encoded_vec.append(vec)
    return np.array(encoded_vec).reshape([sentence_length, dim])

In [7]:
ps = positional_encoding1(10, 20)
ps.shape

(10, 20)

In [15]:
ps[:3]

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [8.41470985e-01, 9.21796446e-01, 1.57826640e-01, 9.98010124e-01,
        2.51162229e-02, 9.99950000e-01, 3.98106119e-03, 9.99998744e-01,
        6.30957303e-04, 9.99999968e-01, 9.99999998e-05, 9.99999999e-01,
        1.58489319e-05, 1.00000000e+00, 2.51188643e-06, 1.00000000e+00,
        3.98107171e-07, 1.00000000e+00, 6.30957344e-08, 1.00000000e+00],
       [9.09297427e-01, 6.99417376e-01, 3.11697146e-01, 9.92048417e-01,
        5.02165994e-02, 9.99800007e-01, 7.96205928e-03, 9.99994976e-01,
        1.26191435e-03, 9.99999874e-01, 1.99999999e-04, 9.99999997e-01,
        3.16978638e-05, 1.00000000e+00, 5.02377286e-06, 1.0000

In [11]:
# simple하게 표현 
def positional_encoding2(sentence_length, dim):
    encoded_vec = np.array([pos/10000**(2*i/dim) for pos in range(sentence_length) for i in range(dim)])
    encoded_vec[::2] = np.sin(encoded_vec[::2])
    encoded_vec[1::2] = np.cos(encoded_vec[1::2])
    return np.array(encoded_vec).reshape([sentence_length, dim])

In [12]:
ps = positional_encoding2(10, 20)
ps.shape

In [14]:
ps[:3]

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [8.41470985e-01, 9.21796446e-01, 1.57826640e-01, 9.98010124e-01,
        2.51162229e-02, 9.99950000e-01, 3.98106119e-03, 9.99998744e-01,
        6.30957303e-04, 9.99999968e-01, 9.99999998e-05, 9.99999999e-01,
        1.58489319e-05, 1.00000000e+00, 2.51188643e-06, 1.00000000e+00,
        3.98107171e-07, 1.00000000e+00, 6.30957344e-08, 1.00000000e+00],
       [9.09297427e-01, 6.99417376e-01, 3.11697146e-01, 9.92048417e-01,
        5.02165994e-02, 9.99800007e-01, 7.96205928e-03, 9.99994976e-01,
        1.26191435e-03, 9.99999874e-01, 1.99999999e-04, 9.99999997e-01,
        3.16978638e-05, 1.00000000e+00, 5.02377286e-06, 1.0000

In [18]:
sentence_length = 10
dim = 20

encoded_vec = np.array([pos/100000**(2*i/dim) for pos in range(sentence_length) for i in range(dim)])

encoded_vec[::2] = np.sin(encoded_vec[::2])
encoded_vec[1::2] = np.cos(encoded_vec[1::2])

encoded_vec.reshape([sentence_length, dim])[:3]
#using convert to tensor

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [8.41470985e-01, 9.50415280e-01, 9.98334166e-02, 9.99500042e-01,
        9.99983333e-03, 9.99995000e-01, 9.99999833e-04, 9.99999950e-01,
        9.99999998e-05, 9.99999999e-01, 1.00000000e-05, 1.00000000e+00,
        1.00000000e-06, 1.00000000e+00, 1.00000000e-07, 1.00000000e+00,
        1.00000000e-08, 1.00000000e+00, 1.00000000e-09, 1.00000000e+00],
       [9.09297427e-01, 8.06578410e-01, 1.98669331e-01, 9.98000667e-01,
        1.99986667e-02, 9.99980000e-01, 1.99999867e-03, 9.99999800e-01,
        1.99999999e-04, 9.99999998e-01, 2.00000000e-05, 1.00000000e+00,
        2.00000000e-06, 1.00000000e+00, 2.00000000e-07, 1.0000